-- MySQL Script generated by MySQL Workbench
-- Thu Oct 25 15:37:25 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Padish
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Padish
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Padish` DEFAULT CHARACTER SET utf8mb4 ;
USE `Padish` ;

-- -----------------------------------------------------
-- Table `Padish`.`CRolCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`CRolCuenta` (
  `id_rol` INT NOT NULL AUTO_INCREMENT,
  `des_rol` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MCuenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MCuenta` (
  `id_cta` INT NOT NULL AUTO_INCREMENT,
  `eml_cta` VARCHAR(45) NOT NULL,
  `usu_cta` VARCHAR(20) NOT NULL,
  `pas_cta` VARCHAR(25) NOT NULL,
  `id_rol` INT NULL,
  PRIMARY KEY (`id_cta`),
  INDEX `id_rol_idx` (`id_rol` ASC),
  CONSTRAINT `id_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `Padish`.`CRolCuenta` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`CDelegacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`CDelegacion` (
  `id_del` INT NOT NULL AUTO_INCREMENT,
  `des_del` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_del`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MUsuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MUsuarios` (
  `id_usu` INT NOT NULL AUTO_INCREMENT,
  `nom_usu` VARCHAR(60) NOT NULL,
  `cur_usu` VARCHAR(18) NOT NULL,
  `dir_usu` VARCHAR(60) NOT NULL,
  `id_cta` INT NULL,
  `id_del` INT NULL,
  PRIMARY KEY (`id_usu`),
  INDEX `id_cta_idx` (`id_cta` ASC),
  INDEX `id_del_idx` (`id_del` ASC),
  CONSTRAINT `id_cta`
    FOREIGN KEY (`id_cta`)
    REFERENCES `Padish`.`MCuenta` (`id_cta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_del`
    FOREIGN KEY (`id_del`)
    REFERENCES `Padish`.`CDelegacion` (`id_del`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`CDisponibilidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`CDisponibilidad` (
  `id_dis` INT NOT NULL AUTO_INCREMENT,
  `des_dis` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_dis`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`CTipoArticulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`CTipoArticulo` (
  `id_art` INT NOT NULL AUTO_INCREMENT,
  `des_art` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_art`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`CTipoProblema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`CTipoProblema` (
  `id_prb` INT NOT NULL AUTO_INCREMENT,
  `des_prb` VARCHAR(250) NOT NULL,
  PRIMARY KEY (`id_prb`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`DPrestadorReceptor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`DPrestadorReceptor` (
  `id_prm` INT NOT NULL AUTO_INCREMENT,
  `id_cta` INT NULL,
  PRIMARY KEY (`id_prm`),
  INDEX `id_cta_idx` (`id_cta` ASC),
  CONSTRAINT `id_cta`
    FOREIGN KEY (`id_cta`)
    REFERENCES `Padish`.`MCuenta` (`id_cta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`DSolicitanteEmisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`DSolicitanteEmisor` (
  `id_sem` INT NOT NULL AUTO_INCREMENT,
  `id_cta` INT NULL,
  PRIMARY KEY (`id_sem`),
  INDEX `id_cta_idx` (`id_cta` ASC),
  CONSTRAINT `id_cta`
    FOREIGN KEY (`id_cta`)
    REFERENCES `Padish`.`MCuenta` (`id_cta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MChat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MChat` (
  `id_cht` INT NOT NULL AUTO_INCREMENT,
  `id_sem` INT NULL,
  `id_prm` INT NULL,
  PRIMARY KEY (`id_cht`),
  INDEX `id_sem_idx` (`id_sem` ASC),
  INDEX `id_prm_idx` (`id_prm` ASC),
  CONSTRAINT `id_sem`
    FOREIGN KEY (`id_sem`)
    REFERENCES `Padish`.`DSolicitanteEmisor` (`id_sem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prm`
    FOREIGN KEY (`id_prm`)
    REFERENCES `Padish`.`DPrestadorReceptor` (`id_prm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MReporteProblema`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MReporteProblema` (
  `id_rep` INT NOT NULL AUTO_INCREMENT,
  `com_rep` VARCHAR(200) NOT NULL,
  `id_prb` INT NULL,
  `id_cta` INT NULL,
  PRIMARY KEY (`id_rep`),
  INDEX `id_cta_idx` (`id_cta` ASC),
  INDEX `id_prb_idx` (`id_prb` ASC),
  CONSTRAINT `id_cta`
    FOREIGN KEY (`id_cta`)
    REFERENCES `Padish`.`MCuenta` (`id_cta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prb`
    FOREIGN KEY (`id_prb`)
    REFERENCES `Padish`.`CTipoProblema` (`id_prb`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MCitas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MCitas` (
  `id_cit` INT NOT NULL AUTO_INCREMENT,
  `lug_cit` VARCHAR(60) NOT NULL,
  `dia_cit` DATE NOT NULL,
  `hor_cit` TIME NOT NULL,
  `id_sem` INT NULL,
  `id_prm` INT NULL,
  PRIMARY KEY (`id_cit`),
  INDEX `id_sem_idx` (`id_sem` ASC),
  INDEX `id_prm_idx` (`id_prm` ASC),
  CONSTRAINT `id_sem`
    FOREIGN KEY (`id_sem`)
    REFERENCES `Padish`.`DSolicitanteEmisor` (`id_sem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_prm`
    FOREIGN KEY (`id_prm`)
    REFERENCES `Padish`.`DPrestadorReceptor` (`id_prm`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MAnuncios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MAnuncios` (
  `id_anu` INT NOT NULL AUTO_INCREMENT,
  `nom_anu` VARCHAR(30) NOT NULL,
  `des_anu` VARCHAR(400) NOT NULL,
  `img_anu` VARCHAR(40) NOT NULL,
  `id_del` INT NULL,
  `id_dis` INT NULL,
  `id_art` INT NULL,
  `id_cta` INT NULL,
  PRIMARY KEY (`id_anu`),
  INDEX `id_del_idx` (`id_del` ASC),
  INDEX `id_dis_idx` (`id_dis` ASC),
  INDEX `id_art_idx` (`id_art` ASC),
  INDEX `id_cta_idx` (`id_cta` ASC),
  CONSTRAINT `id_del`
    FOREIGN KEY (`id_del`)
    REFERENCES `Padish`.`CDelegacion` (`id_del`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_dis`
    FOREIGN KEY (`id_dis`)
    REFERENCES `Padish`.`CDisponibilidad` (`id_dis`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_art`
    FOREIGN KEY (`id_art`)
    REFERENCES `Padish`.`CTipoArticulo` (`id_art`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_cta`
    FOREIGN KEY (`id_cta`)
    REFERENCES `Padish`.`MCuenta` (`id_cta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Padish`.`MHistorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Padish`.`MHistorial` (
  `id_his` INT NOT NULL AUTO_INCREMENT,
  `id_anu` INT NULL,
  PRIMARY KEY (`id_his`),
  INDEX `id_anu_idx` (`id_anu` ASC),
  CONSTRAINT `id_anu`
    FOREIGN KEY (`id_anu`)
    REFERENCES `Padish`.`MAnuncios` (`id_anu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
